version: 2.1

orbs:
  win: circleci/windows@2.2.0 

workflows:
  build-and-deploy-to-heroku:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run:
          name: echo password
          command: echo $SA_PWD
      - run:
          name: Run SQL Server 2019 docker container
          command:  docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$SA_PWD" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore src\Cfd
      - run:
          name: Build project 
          command: dotnet build src\Cfd
  
   
    

      
            
